### PR TITLE
Create Postgres table schema using Knex + bookshelf.

### PR DESCRIPTION
**Pull request by brianpchsu**

### CODE REVIEW

**Comment by rebekahkwon** [comment]
Looking at it now.

**Comment by bportnoy** [comment]
For elections, the start and end times should be datetime rather than just time, and privacy_stategy should be a string rather than a JSON object.
For questions, I think the options should be a JSON object.
For results, the results should be a JSON object rather than text.

And let's add timestamps for everything - can't hurt.

**Comment by rebekahkwon** [comment]
Also, please add a description field (text) to elections for <1000 characters.

**Comment by rebekahkwon** [comment]
Additionally, please add a URL_HANDLE column (str), unless there's reason to randomize the endpoint. Thoughts?

**Comment by bportnoy** [comment]
Should 2fa have 3 options? Enabled, Disabled, Forced?

**Comment by rebekahkwon** [comment]
Yes, let's add that in.

**Comment by rebekahkwon** [comment]
I think it looks good, so I'll merge and make the change.

**Comment by ryyann** [comment]
It should be an additional boolean if we're doing that (ie "force_2_auth"), it seems weird that it would be stored as a string.

**Pull request merged**
